[package]
name = "lsdirs"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "^0.4.0"
clap = { version = "^4.0.0", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
